{% set name = "safetensors" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/safetensors/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e96a3b89093bf9e3dfea02283b05b8517fe3ad4b632ab20266392688e4ca18d7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib64/libgcc_s.so.1  # [linux]
  script:
    {% if build_platform != target_platform %}
    - export PYO3_CROSS_INCLUDE_DIR=$PREFIX/include
    - export PYO3_CROSS_LIB_DIR=$SP_DIR/../
    - export PYO3_CROSS_PYTHON_VERSION=$PY_VER
    {% endif %}
    - cd bindings/python
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - setuptools-rust
    - pip
    - tomli
    - maturin >=1.0,<2.0
  run:
    - python

test:
  imports:
    - safetensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/safetensors
  summary: Fast and Safe Tensor serialization
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - setu4993
