{% set name = "safetensors" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/safetensors-{{ version }}.tar.gz
  sha256: edb7072d788c4f929d0f5735d3a2fb51e5a27f833587828583b7f5747af1a2b8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - setuptools-rust
    - pip
    - tomli
  run:
    - python

test:
  imports:
    - safetensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/safetensors
  summary: Fast and Safe Tensor serialization
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
