{% set name = "safetensors" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/safetensors-{{ version }}.tar.gz
  sha256: b985953c3cf11e942eac4317ef3db3da713e274109cf7cfb6076d877054f013e

build:
  number: 0
  script:
    {% if build_platform != target_platform %}
    - export PYO3_CROSS_INCLUDE_DIR=$PREFIX/include
    - export PYO3_CROSS_LIB_DIR=$SP_DIR/../
    - export PYO3_CROSS_PYTHON_VERSION=$PY_VER
    - export PYO3_PYTHON_VERSION=$PY_VER
    {% endif %}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools-rust
    - maturin >=1.0,<2.0
    - tomli
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - safetensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/safetensors
  summary: Fast and Safe Tensor serialization
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - setu4993
