{% set name = "safetensors" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/safetensors-{{ version }}.tar.gz
  sha256: c47b34c549fa1e0c655c4644da31332c61332c732c47c8dd9399347e9aac69d1

build:
  number: 0
  script:
    # PyPy has weird sysconfigdata name
    - rm -f $PREFIX/lib/pypy$PY_VER/_sysconfigdata.py  # [build_platform != target_platform and target_platform == "linux-ppc64le"]
    - {{ PYTHON }} -m pip install . -vv
    - cd safetensors && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - setuptools-rust
    - maturin >=1.0,<2.0
    - tomli
  run:
    - python

test:
  imports:
    - safetensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/safetensors
  summary: Fast and Safe Tensor serialization
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - jan-janssen
    - setu4993
    - xhochy
